apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidateprofileui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidateprofileui
  template:
    metadata:
      labels:
        app: candidateprofileui
    spec:
      containers:
        - name: candidateprofileui
          image: unifiedassessprod.azurecr.io/candidate_profile_ui:$tag
          resources:
           limits:
             cpu: "200m"
             memory: "200Mi"
           requests:
             cpu: "150m"
             memory: "100Mi"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret